version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.6
  working_directory: ~/marquez_airflow


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install airflow from package
          environment:
            SLUGIFY_USES_TEXT_UNIDECODE: 'yes'
          command: pip install --user -e .
      - run: pip install --user flake8
      - run: python -m flake8

  test:
    <<: *defaults
    steps:
      - checkout
      - run: pip install --user pytest
      - run: pip install --user pytest-cov
      - run: pip install --user codecov
      - run:
          name: Install airflow from package
          environment:
            SLUGIFY_USES_TEXT_UNIDECODE: 'yes'
          command: pip install --user -e .
      - run: python -m pytest --cov=marquez --cov-report xml ./test

  integration-test:
    <<: *defaults
    steps:
      - checkout
      - run: pip install --user pytest

  release:
    <<: *defaults
    steps:
      - checkout
      - run: pip install --user twine
      - run: python setup.py sdist
      - run: python -m twine upload --verbose dist/*

workflows:
  version: 2
  marquez_airflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}$/
            branches:
              ignore: /.*/
